---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: annuaire
  name: annuaire-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: annuaire-sc # Doit correspondre à la storageClass du PV

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: annuaire
  name: annuaire-mariadb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Utilisé pour une base de données avec un seul pod
  persistentVolumeReclaimPolicy: Retain # Conserve les données après suppression du PVC
  storageClassName: annuaire-sc # Optionnel, pour une classe de stockage spécifique
  nfs:
    path: /volume1/kubernetes/mariadb-annuaire/
    server: 192.168.100.251 # Adresse IP du NAS
  mountOptions:
    - nfsvers=4.1
