apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-pod
  namespace: annuaire
spec:
  serviceName: mariadb-service
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-pod
  template:
    metadata:
      labels:
        app: mariadb-pod
    spec:
      initContainers:
        - name: init-permissions
          image: mariadb:lts-noble
          command:
            [
              "sh",
              "-c",
              "chown -R mysql:mysql /var/lib/mysql && chmod -R 750 /var/lib/mysql",
            ]
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mariadb-container
          image: mariadb:lts-noble
          env:
            - name: TZ
              value: Europe/Paris
            - name: DB_HOST
              value: "mariadb"
            - name: MARIADB_VERSION
              value: "1:11.1.2+maria~ubu2204"
            - name: MARIADB_ROOT_PASSWORD
              value: "annuaire_root_pass" # Mot de passe root pour MariaDB
            - name: MARIADB_USER
              value: "annuaire_usr" # Nom d'utilisateur pour la base de données
            - name: MARIADB_PASSWORD
              value: "annuaire_pass" # Mot de passe pour l'utilisateur
            - name: MARIADB_DATABASE
              value: "annuaire_db" # Nom de la base de données
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql # Chemin où MariaDB stocke ses données
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: annuaire-mariadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: annuaire
spec:
  selector:
    app: mariadb-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
