apiVersion: v1
kind: ConfigMap
metadata:
  name: annuaire-config
  namespace: annuaire
data:
  TZ: Europe/Paris
  DATABASE_URL: postgresql+psycopg2://annuaire_user:annuaire_password@postgres-svc:5432/annuaire_contacts
  LOG_LEVEL: INFO
