apiVersion: v1
kind: ConfigMap
metadata:
  name: annuaire-config
  namespace: annuaire
data:
  TZ: Europe/Paris
  DATABASE_URL: mysql+pymysql://annuaire_usr:annuaire_pass@mariadb-svc:3306/annuaire_db
  LOG_LEVEL: INFO
